# Generated by Django 5.0.4 on 2024-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, verbose_name='Name')),
                ('cemail', models.CharField(max_length=100, verbose_name='Email')),
                ('cmobile', models.IntegerField()),
                ('cgender', models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], verbose_name='Gender')),
                ('cstatus', models.IntegerField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], verbose_name='Marrital Status')),
                ('caadhar', models.IntegerField()),
                ('caddress', models.CharField(max_length=300, verbose_name='Address')),
                ('cpincode', models.IntegerField()),
                ('cdate', models.DateTimeField()),
            ],
        ),
    ]
