# Generated by Django 5.0.4 on 2024-04-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasutilityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, verbose_name='Name')),
                ('cemail', models.CharField(max_length=100, verbose_name='Email')),
                ('cmobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('cgender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('cstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, verbose_name='Marrital Status')),
                ('caadhar', models.CharField(max_length=12, verbose_name='Aadhar Card Number')),
                ('caddress', models.CharField(max_length=300, verbose_name='Address')),
                ('cpincode', models.IntegerField()),
                ('cdob', models.DateTimeField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
