# Generated by Django 5.0.4 on 2024-04-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasutilityapp', '0002_connections_delete_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('ref', models.CharField(choices=[('5 - Rs.500', '5 - Rs.500'), ('10 - Rs.800', '10 - Rs.800'), ('15 - Rs.1000', '15 - Rs.1000'), ('20 - Rs.1500', '20 - Rs.1500'), ('25 - Rs.1800', '25 - Rs.1800'), ('30 - Rs.2000', '30 - Rs.2000')], max_length=20, verbose_name='Reffiling')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='null', max_length=15, verbose_name='Delivery Status')),
                ('bookdate', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasutilityapp.connections')),
            ],
        ),
    ]
