# Generated by Django 5.0.4 on 2024-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasutilityapp', '0003_bookinggass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinggass',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='in progress', max_length=15, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='cdob',
            field=models.DateField(),
        ),
    ]
